manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.6.1
      import: true
    # Drivers repository
    - name: zephyr-driver-work-v2
      path: kionix-drivers
      revision: main
#      url: git@github.com:tedhavelka/zephyr-driver-work-v2
      url: https://github.com/tedhavelka/zephyr-driver-work-v2
#      import: true   ...2021-08-26 for some reason this should be commented out - TMH
  self:
    # This repository should be cloned to 
    path: kionix-driver-demo
