manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.6.1
      import: true
    # Drivers repository
    - name: zephyr-driver-work-v2
      path: kionix-drivers
      revision: main
#      revision: 299b507b8eb372771aa543f315fc95178cb80029
      url: git@github.com:tedhavelka/zephyr-driver-work-v2
#      import: true
  self:
    # This repository should be cloned to 
    path: kionix-driver-demo
