manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
      revision: v3.2.0
      import: true

    # Kionix driver work repository, name of remote repository followed by name of local dir into which to clone:
    - name: zephyr-driver-work-v2
      path: kionix-drivers
#      revision: main
      revision: main
      url: https://github.com/tedhavelka/zephyr-driver-work-v2

  self:
    # This repository should be cloned to 
    path: kionix-driver-demo
