#ifndef _KIONIX_DRIVER_ERRORS_H
#define _KIONIX_DRIVER_ERRORS_H


enum kionix_demo_errors_e
{
    KD_FIRST_ENUMERATED_ERROR = 0,
    KD_ERROR__HANDLE_TO_ALTERNATE_UART_NULL,
    KD_ERROR__COUNT_OF_DEFINED_ERRORS
};


#endif // _KIONIX_DRIVER_ERRORS_H
