#ifndef _KD_ROUTINE_OPTIONS_H
#define _KD_ROUTINE_OPTIONS_H

enum kionix_demo_routine_options_e
{
    KD_ROUTINE_OPTION_FIRST,
    KD_ROUTINE_OPTION__RETURN_APP_VERSION,
    KD_ROUTINE_OPTION__RETURN_AND_DISPLAY_APP_VERSION,
    KD_ROUTINE_OPTION_COUNT,
};

#endif // _KD_ROUTINE_OPTIONS_H
